[theme]
# Thème personnalisé Sensations Arda
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#1f2937"
font = "sans serif"

[server]
# Configuration serveur
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5

[browser]
# Configuration navigateur
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
# Configuration exécution
magicEnabled = true
fastReruns = true